name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  criar-maquina:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  teste-projecto:
    needs: criar-maquina
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automated Tests
        run: |
          python manage.py test

  Producao:
    needs:
      - criar-maquina
      - teste-projecto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automated Tests
        run: |
          python manage.py test

  Apresentacao:
    needs:
      - criar-maquina

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying to production..."

      - name: Criar Branch Master se não existir
        run: |
          git branch -a | grep "remotes/origin/master"
          if [ $? -eq 1 ]; then
            git checkout -b master
            git push origin master
          fi
        # Adicione aqui os comandos necessários para implantar sua aplicação
