name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  criar-maquina:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  teste-projecto:
    needs: criar-maquina
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automated Tests
        run: |
          python manage.py test

  Producao:
    needs:
      - criar-maquina
      - teste-projecto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Automated Tests
        run: |
          python manage.py test

  Criando-Master:
    needs: teste-projecto

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Criar Branch Master se não existir
        run: |
          permissions:
            contents: write
          git ls-remote --heads origin master
          if [ $? -eq 0 ]; then
            git checkout -b master
            git push origin master
          else
            git checkout master
            git pull origin main
            git push origin master
          fi
        

        # Adicione aqui os comandos necessários para implantar sua aplicação
